services:
  frontend:
    build: C:\Users\GIGABYTE I5\Desktop\application web distribué\projet\project-bolt-bolt-angular-dsekv4bu\project
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build: .  # Current directory (Rating-service)
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:h2:file:~/gamificationdbb
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      - SPRING_CLOUD_CONFIG_ENABLED=false
      # Add other properties as needed